# Generated by Django 4.2.3 on 2023-07-10 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_function', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flash_news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
