# Generated by Django 4.2.2 on 2023-07-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_function', '0002_flash_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='flash_news',
            name='sentiment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
